services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=2Secure*Password2
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql

  app:
    build: .
    depends_on:
      - db
    command: /bin/sh -c "sleep 30 && dotnet WebSite.dll"
    environment:
      - ConnectionStrings__Database=Server=localhost,1433;Database=cnab;User Id=SA;Password=2Secure*Password2;TrustServerCertificate=true;
    ports:
      - "5000:80"

volumes:
  mssql-data: